Vehicles integration APIs
twoje-osk/twoje-osk pull request #30
Opened 2022-05-26 21:48 UTC by maonat

Vehicles APIs implementation

## Description
Created API endpoints for the following functions:
- List all Vehicles
- List a specific Vehicle by ID
- Add a new Vehicle
- Edit an existing Vehicle
- Delete an existing Vehicle

Additional functionalities within the implemented functions:
- Check if vehicle with the same license plate already exists

## What part of the app is affected?
* [ ] Frontend
* [x] Backend

## Screenshots or Video Recording (if appropriate):

2022-05-28 22:51 UTC, bibixx requested changes

2022-05-28 22:51 UTC, bibixx commented on backend/src/migrations/1652990197933-CreateVehicles.ts
> +import { MigrationInterface, QueryRunner } from "typeorm";
Let's try to merge those migrations into one:
1. Remove those 3 Migrations
2. Drop all of the tables
3. Run `yarn migrate` to run old migrations
4. Run `yarn create-migration src/migrations/CreateVehicles` to create the new migration with all of the changes in those 3

2022-05-28 22:51 UTC, bibixx commented on backend/src/seeds/seed.vehicles.ts
> +    vehicle.notes = this.faker.random.words(10);
Maybe we could also randomize if the note has a note, or not? 
```suggestion
    vehicle.notes = this.faker.datatype.number({ max: 1, min: 0, precision: 0.0000001 }) < 0.2 ? this.faker.random.words(10) : undefined;
```

We're comparing to 0.2 to have a 20% chance of having a note

2022-05-28 22:51 UTC, bibixx commented on backend/src/vehicles/entities/vehicle.entity.ts
> +@Unique(['licensePlate'])
As we said on a call, we probably shouldn't add a unique check on the DB level not to leak information about license plates in the other organizations

2022-05-28 22:51 UTC, bibixx commented on backend/src/vehicles/vehicles.controller.ts
> +  @ApiCreatedResponse({ type: Vehicle, description: 'Record created' })
Please pull the latest changes from `main` and remove the eslint comment

2022-05-28 22:51 UTC, bibixx commented on backend/src/vehicles/vehicles.controller.ts
> +    await this.vehicleService.update(vehicle, id);
Before updating we should also check if the vehicle with specified license plate already exists

2022-05-28 22:51 UTC, bibixx commented on backend/src/vehicles/vehicles.controller.ts
> +  async addNew(
Let's change it to `create` to follow nest's convention
https://docs.nestjs.com/controllers#full-resource-sample

2022-05-28 22:51 UTC, bibixx commented on backend/src/vehicles/vehicles.controller.ts
> +  async delete(
Let's change it to `remove` to follow nest's convention
https://docs.nestjs.com/controllers#full-resource-sample

2022-05-28 22:51 UTC, bibixx commented on backend/src/vehicles/vehicles.controller.ts
> +  async getAll(): Promise<VehicleGetAllResponseDto> {
Let's change it to `findAll` to follow nest's convention
https://docs.nestjs.com/controllers#full-resource-sample

2022-05-28 22:51 UTC, bibixx commented on backend/src/vehicles/vehicles.service.ts
> +  // create
Let's remove those comments

2022-05-28 22:51 UTC, bibixx commented on backend/src/vehicles/vehicles.service.ts
> +    );
Let's extract the call to the BD (so `this.vehiclesRepository.countBy(/* ... */)`) to a variable (we can call it `numberOfFoundVehicles`) and return only the comparison

```suggestion
    const numberOfFoundVehicles = await this.vehiclesRepository.countBy({
      licensePlate,
      organization: { id: organizationId },
    })

    return numberOfFoundVehicles > 0;
```

2022-05-28 22:51 UTC, bibixx commented on shared/src/dto/vehicle/vehicle.dto.ts
> +  vehicle: DtoVehicle;
That's something I didn't know before, so not really your fault — if you want to validate a nested object you have to add 2 more decorators 😕 `@ValidateNested` (from `class-validator`) and `@Type` (from `class-transformer`, also you'll have to install the `class-transformer` package in the `shared` folder because of that)

```
	@ValidateNested()
  @Type(() => DtoCreateVehicle)
```

2022-05-28 22:51 UTC, bibixx commented on backend/src/vehicles/entities/vehicle.entity.ts
> +  notes?: string;
Also not your fault. Probably you'll have to update some additional types in other places of the app
```suggestion
  @Column({ nullable: true, type: 'text' })
  notes: string | null;
```

2022-05-28 22:51 UTC, bibixx commented on backend/src/vehicles/vehicles.controller.ts
> +    const vehicle = await this.vehicleService.findOneById(+id);
```suggestion
  async findOne(@Param('id', ParseIntPipe) id: number): Promise<VehicleFindOneResponseDto> {
    const vehicle = await this.vehicleService.findOneById(id);
```

2022-05-30 17:44 UTC, maonat commented on backend/src/vehicles/entities/vehicle.entity.ts
> +@Unique(['licensePlate'])
Only this to be changed, we shall keep the check on vehicles on the controller level

2022-05-30 18:41 UTC, maonat commented on backend/src/vehicles/vehicles.controller.ts
> +  async delete(
I would keep it that as "remove" because delete does something else
https://stackoverflow.com/questions/54246615/what-s-the-difference-between-remove-and-delete

2022-06-01 20:09 UTC, bibixx commented on backend/src/vehicles/vehicles.controller.ts
> +  async delete(
I sustain keeping it as `remove` to be in check with NestJS convention

2022-06-01 20:11 UTC, bibixx commented on shared/src/dto/vehicle/vehicle.dto.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-types
Please remove this comment and change the type to `ApiDate` (as suggested by the ESLint rule)

2022-06-01 22:12 UTC, bibixx approved these changes
LGTM now 👍🏻

2022-06-01 22:12 UTC, merged