Fixed error when vehicle try to edit it's own plate with the same one
twoje-osk/twoje-osk pull request #40
Opened 2022-06-14 21:29 UTC by maonat

## Description
In response to [This bug](https://docs.craft.do/editor/d/89c1f630-307d-b790-599c-1660ce95fb35/4c1f0fbe-edd7-46b3-b240-d10809ef0007/b/F9DF55C9-833C-4F9B-AE52-35DE3D258584/When_updating_the_vehicle_with_the_s)
## What part of the app is affected?
* [ ] Frontend
* [x] Backend

## Screenshots or Video Recording (if appropriate):

2022-07-06 17:41 UTC, bibixx requested changes

2022-07-06 17:41 UTC, bibixx commented on backend/src/vehicles/vehicles.service.ts
> +      },
We don't need this relation

2022-07-12 21:01 UTC, maonat commented on backend/src/vehicles/vehicles.service.ts
> +      },
Done

2022-07-13 16:58 UTC, bibixx approved these changes

2022-07-13 23:50 UTC, merged